In [1]:
import numpy as np

# 1.DataTypes & Attributes

In [2]:
# NumPy's main datatype is ndarray
a1=np.array([1,2,3]) #creating a numpy array
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2.0,3.3],
              [4,5,6.5]])

a3 = np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
              
              [[10,11,12],
              [13,14,15],
              [16,17,18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape #shows the number of row, column

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim #ndim shows the dimension of an array

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype #dtype shows the data type of an array

(dtype('int32'), dtype('float64'), dtype('int32'))

In [12]:
a1.size, a2.size, a3.size #size shows the no of element in an array

(3, 6, 18)

In [13]:
# Create a Dataframe from a NumPy array
import pandas as pd

df=pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

# 2.Creating arrays

In [14]:
ones=np.ones((2,3)) #create an array of 1 of given shape
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
ones.dtype

dtype('float64')

In [16]:
zeros=np.zeros((2,3)) #create an array of 0 of given shape
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
range_array=np.arange(0,10,2)#arange describes start, stop, step
range_array

array([0, 2, 4, 6, 8])

In [18]:
random_array=np.random.randint(0,10,size=(3,5)) #randint describes start, stop, shape
random_array

array([[8, 2, 8, 5, 9],
       [7, 8, 3, 3, 0],
       [0, 2, 5, 8, 2]])

In [19]:
random_array.size

15

In [20]:
random_array.shape

(3, 5)

In [21]:
random_array_1=np.random.rand(5,3)
random_array_1

array([[0.39021623, 0.25967108, 0.25521061],
       [0.52008581, 0.94045229, 0.15274661],
       [0.49230914, 0.58669807, 0.79263863],
       [0.5424005 , 0.2170101 , 0.26265779],
       [0.40498527, 0.4610359 , 0.07416937]])

In [22]:
np.random.seed(0) #seed(any number) fixes the randomization
random_array_2=np.random.randint(10,size=(5,3))
random_array_2

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [23]:
np.unique(random_array_2) #unique shows the elements of random_array_2 only once

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Viewing arrays & matrices

In [24]:
a1

array([1, 2, 3])

In [25]:
a1[0]

1

In [26]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [27]:
a2[0]

array([1. , 2. , 3.3])

In [28]:
a2[1]

array([4. , 5. , 6.5])

In [29]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [30]:
a3[0,0]

array([1, 2, 3])

In [31]:
a3[1,1]

array([13, 14, 15])

# Manipulating arrays

In [32]:
a1

array([1, 2, 3])

In [33]:
Ones=np.ones(3)
Ones

array([1., 1., 1.])

In [34]:
a1+Ones

array([2., 3., 4.])

In [35]:
a1-Ones

array([0., 1., 2.])

In [36]:
a1*Ones

array([1., 2., 3.])

In [37]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [38]:
a1*a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [39]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [40]:
#a2*a3 #need to reshape

In [41]:
a1/Ones

array([1., 2., 3.])

In [42]:
a2/a1 # / means division and it shows the division with decimals

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [43]:
a2//a1 #Floor division removes the decimals (round down)

array([[1., 1., 1.],
       [4., 2., 2.]])

In [44]:
a1

array([1, 2, 3])

In [45]:
a1/2

array([0.5, 1. , 1.5])

In [46]:
a1%2 #Mod shows the remainder

array([1, 0, 1], dtype=int32)

In [47]:
a2**2 #power 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [48]:
np.square(a2)# function for power

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [49]:
np.add(a1,Ones) #same as a1+Ones

array([2., 3., 4.])

In [50]:
np.log(a1) 

array([0.        , 0.69314718, 1.09861229])

In [51]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [52]:
np.mean(a2) #aggregation,,means action aplly on the group of data

3.6333333333333333

In [53]:
np.max(a2)

6.5

In [54]:
np.min(a2)

1.0

In [55]:
np.var(a2)

3.3222222222222224

In [56]:
np.std(a2) #std means the difference from the mean value. low std represents a good result, high std represents the bad result.

1.8226964152656422

In [57]:
#Standard Deviation= squareroot of variance
np.sqrt(np.var(a2))

1.8226964152656422

# Reshape & Transpose

In [59]:
a2.shape

(2, 3)

In [60]:
a3.shape

(2, 3, 3)

In [61]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [62]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [63]:
a2.reshape(2,3,1)

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [64]:
a2_reshape=a2.reshape(2,3,1)
a2_reshape

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [65]:
a2_reshape.shape

(2, 3, 1)

In [66]:
a2_reshape*a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [67]:
a2.T #T switches the axises

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [68]:
a3.T

array([[[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]]])

In [69]:
a3.T.shape

(3, 3, 2)

# Comparison Operators

In [70]:
a1

array([1, 2, 3])

In [71]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [72]:
a1>a2

array([[False, False, False],
       [False, False, False]])

In [73]:
a1>=a2

array([[ True,  True, False],
       [False, False, False]])

In [74]:
bool_array=a1>=a2
bool_array

array([[ True,  True, False],
       [False, False, False]])

In [75]:
type(bool_array), bool_array.dtype

(numpy.ndarray, dtype('bool'))

In [76]:
a1>5

array([False, False, False])

In [77]:
a1<5

array([ True,  True,  True])

In [78]:
a1 == a1

array([ True,  True,  True])

In [79]:
a1 == a2

array([[ True,  True, False],
       [False, False, False]])

In [80]:
a1!=a2

array([[False, False,  True],
       [ True,  True,  True]])

# Sorting arrays

In [81]:
unsorted=np.random.randint(10,size=(5,3))
unsorted

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [82]:
np.sort(unsorted) #shows the ascending ordered array

array([[6, 7, 7],
       [1, 5, 8],
       [8, 9, 9],
       [0, 3, 4],
       [0, 3, 5]])

In [83]:
np.argsort(unsorted)#arg sorts the index numbers 

array([[0, 1, 2],
       [1, 2, 0],
       [1, 0, 2],
       [2, 1, 0],
       [2, 0, 1]], dtype=int64)

In [84]:
np.argsort(a1)

array([0, 1, 2], dtype=int64)

In [85]:
np.argmin(a1) #shows the index no of the lowest number in an array

0

In [86]:
np.argmax(a1)#shows the index no of the maximum number in an array

2

# Turn image into an numpy array

In [87]:
from matplotlib.image import imread

<img src= "image/panda.png"/>

In [88]:
panda=imread("image/panda.png")
type(panda)

numpy.ndarray

In [89]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [90]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

In [91]:
panda[:5]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.

<img src ="image/dog-photo.png"/>

In [92]:
dog=imread("image/dog-photo.png")
type(dog)

numpy.ndarray

In [93]:
dog

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]],

       [[0.69411767, 0.8039216 , 0.8862745 , 1.        ],
        [0.7019608 , 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49411765, 0.68235296, 0.84313726, 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ]],

       [[0.6901961 , 0.8       , 0.88235295, 1.        ],
        [0.69803923, 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49803922, 0.686274

In [94]:
dog[:1]

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]]], dtype=float32)

<img src= "image/car-photo.png"/>

In [96]:
car=imread("image/car-photo.png")
type(car)

numpy.ndarray

In [97]:
car

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.482352

In [98]:
car[:1]

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]]], dtype=float32)